name: Backend SonarCloud analysis

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'back/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  backsonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
            path: ~/.m2
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      - name: Build backend with Maven
        run: mvn clean verify
        working-directory: back


      - name: Analyse SonarQube for backend
        working-directory: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=booster39_back_bobapp \
          -Dsonar.projectName=booster39_back_bobapp \
          -Dsonar.organization=booster39

      - name: Upload backend test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: back/target/site/jacoco/jacoco.xml