name: Frontend SonarCloud analysis

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'front/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  ci-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node.js Configuration
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'


      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing dependencies
        working-directory: front
        run: npm ci


      - name: Executing tests
        working-directory: front
        run:  npm run test --browsers=ChromeHeadless

      - name: Analyse SonarQube for frontend
        working-directory: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
        run: |
          npx sonar-scanner \
          -Dsonar.projectKey=booster39_front_bobapp \
          -Dsonar.sources=. \
          -Dsonar.projectName=booster39_front_bobapp \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=booster39 \
          -Dsonar.token=${{ secrets.SONAR_TOKEN_FRONT }} \
          -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info \
          -Dsonar.exclusions="**/*.spec.ts, **/*.test.ts, **/tests/**"


      - name: Upload frontend test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: front/coverage/bobapp/lcov.info