name: Frontend SonarCloud analysis

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'front/**'

jobs:
  ci-frontend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Vérifier le code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Node.js
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'


      # Étape 4 : Cache des modules Node.js
      - name: Mettre en cache les modules Node.js
        uses: actions/cache@v4
        with:
          path: front/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Étape 5 : Installation des dépendances
      - name: Installation des dépendances
        working-directory: front
        run: npm ci


      # Étape 8 : Lancement des tests
      - name: Lancement des tests
        working-directory: front
        run:  npm run test:prod -- --browsers=ChromeHeadless

      # Étape 9 : Analyse SonarQube pour le frontend
      - name: Analyse SonarQube pour le frontend
        working-directory: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
        run: |
          npx sonar-scanner \
          -Dsonar.projectKey=booster39_front_bobapp \
          -Dsonar.sources=. \
          -Dsonar.projectName=booster39_front_bobapp \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=booster39 \
          -Dsonar.token=${{ secrets.SONAR_TOKEN_FRONT }} \
          -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info \
          -Dsonar.exclusions="**/*.spec.ts, **/*.test.ts, **/tests/**"


      # Étape 11 : Upload des résultats de test frontend
      - name: Upload des résultats de tests frontend
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: front/coverage/bobapp/lcov.info