name: Build Docker Images (Front & Back)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images with Compose
        run: docker-compose -f docker-compose.yml build
