name: CD Workflow Frontend

on:
  workflow_run:
    workflows: ["Frontend SonarCloud analysis"]
    types:
      - completed

jobs:
  cd-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4



      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Construction et push de l'image Docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: front
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest