name: Build Backend Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build ./back --file ./back/Dockerfile --tag bobapp-back:latest
